# This source file is part of the Greatdori! open source project
#
# Copyright (c) 2025 the Greatdori! project authors
# Licensed under Apache License v2.0
#
# See https://greatdori.com/LICENSE.txt for license information
# See https://greatdori.com/CONTRIBUTORS.txt for the list of Greatdori! project authors

blank_issues_enabled: true
contact_links:
  - name: ðŸŒ Discuss an idea
    url: https://github.com/Greatdori/DoriKit/discussions
    about: >
      Share an idea with the community.
