#===---*- Greatdori! -*----------------------------------------------------===#
#
# build-dorikit.yml
#
# This source file is part of the Greatdori! open source project
#
# Copyright (c) 2025 the Greatdori! project authors
# Licensed under Apache License v2.0
#
# See https://greatdori.com/LICENSE.txt for license information
# See https://greatdori.com/CONTRIBUTORS.txt for the list of Greatdori! project authors
#
#===-----------------------------------------------------------------------===#

name: Build DoriKit

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: macos-26
    strategy:
      matrix:
        destination: ["macOS", "macOS,variant=Mac Catalyst", "iOS Simulator", "iOS", "watchOS Simulator", "watchOS"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Remove runner local related libs
        run: brew remove --ignore-dependencies libssh2
      - name: Create build folder
        run: mkdir build
      - name: Build
        run: xcodebuild -project DoriKit.xcodeproj -scheme DoriKit -configuration Release -derivedDataPath ./build -destination "generic/platform=${{ matrix.destination }}" build
      - name: Upload build result
        uses: actions/upload-artifact@v4.6.2
        with:
          name: DoriKit-${{ endsWith(matrix.destination, 'Mac Catalyst') && 'Mac Catalyst' || matrix.destination }}.framework
          path: ./build/Build/Products/*/DoriKit.framework
          if-no-files-found: error
